"""assessment, claim library, contract playbook (B2 agents)

Revision ID: 065eae42b2ad
Revises: 978621b2b340
Create Date: 2026-07-07 14:41:52.151533
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '065eae42b2ad'
down_revision: Union[str, None] = '978621b2b340'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assessment',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('subject', sa.String(), nullable=False),
    sa.Column('risk_rating', sa.String(), nullable=False),
    sa.Column('lawful_basis', sa.String(), nullable=True),
    sa.Column('data_categories', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cross_border', sa.Boolean(), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_workflow_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_assessment_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment'))
    )
    op.create_index(op.f('ix_assessment_organization_id'), 'assessment', ['organization_id'], unique=False)
    op.create_table('claim_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('market', sa.String(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('substantiation_ref', sa.String(), nullable=True),
    sa.Column('regulated', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_claim_entry_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_claim_entry'))
    )
    op.create_index(op.f('ix_claim_entry_organization_id'), 'claim_entry', ['organization_id'], unique=False)
    op.create_index('ix_claim_entry_product', 'claim_entry', ['organization_id', 'product', 'market'], unique=False)
    op.create_table('contract_playbook',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('contract_type', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('mandatory_clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('forbidden_clauses', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('negotiable_bands', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_contract_playbook_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_contract_playbook')),
    sa.UniqueConstraint('organization_id', 'contract_type', 'version', name='uq_contract_playbook_type_version')
    )
    op.create_index(op.f('ix_contract_playbook_organization_id'), 'contract_playbook', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contract_playbook_organization_id'), table_name='contract_playbook')
    op.drop_table('contract_playbook')
    op.drop_index('ix_claim_entry_product', table_name='claim_entry')
    op.drop_index(op.f('ix_claim_entry_organization_id'), table_name='claim_entry')
    op.drop_table('claim_entry')
    op.drop_index(op.f('ix_assessment_organization_id'), table_name='assessment')
    op.drop_table('assessment')
    # ### end Alembic commands ###
