"""workflow engine tables + intake front door columns

Revision ID: 0da74f905cfe
Revises: d61aee16e3e7
Create Date: 2026-07-07 12:03:12.988839
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0da74f905cfe'
down_revision: Union[str, None] = 'd61aee16e3e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definition',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workflow_definition_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_definition')),
    sa.UniqueConstraint('organization_id', 'key', 'version', name='uq_workflow_definition_org_key_version')
    )
    op.create_index(op.f('ix_workflow_definition_organization_id'), 'workflow_definition', ['organization_id'], unique=False)
    op.create_table('workflow_instance',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('definition_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('current_step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('started_by', sa.String(), nullable=True),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('step_entered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_instance_definition_id_workflow_definition')),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_workflow_instance_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_instance'))
    )
    op.create_index(op.f('ix_workflow_instance_definition_id'), 'workflow_instance', ['definition_id'], unique=False)
    op.create_index('ix_workflow_instance_entity', 'workflow_instance', ['organization_id', 'entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_workflow_instance_organization_id'), 'workflow_instance', ['organization_id'], unique=False)
    op.create_index(op.f('ix_workflow_instance_status'), 'workflow_instance', ['status'], unique=False)
    op.create_table('workflow_step',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('definition_id', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('screen_key', sa.String(), nullable=False),
    sa.Column('approver_role', sa.String(), nullable=True),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('agent_config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('step_order BETWEEN 1 AND 15', name=op.f('ck_workflow_step_workflow_step_order_range')),
    sa.ForeignKeyConstraint(['definition_id'], ['workflow_definition.id'], name=op.f('fk_workflow_step_definition_id_workflow_definition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_step')),
    sa.UniqueConstraint('definition_id', 'step_order', name='uq_workflow_step_definition_order')
    )
    op.create_index(op.f('ix_workflow_step_definition_id'), 'workflow_step', ['definition_id'], unique=False)
    op.create_table('workflow_agent_task',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('step_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('output', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], name=op.f('fk_workflow_agent_task_instance_id_workflow_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_agent_task'))
    )
    op.create_index(op.f('ix_workflow_agent_task_instance_id'), 'workflow_agent_task', ['instance_id'], unique=False)
    op.create_table('workflow_transition',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('instance_id', sa.String(), nullable=False),
    sa.Column('from_step_order', sa.Integer(), nullable=False),
    sa.Column('to_step_order', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_label', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instance.id'], name=op.f('fk_workflow_transition_instance_id_workflow_instance'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workflow_transition'))
    )
    op.create_index(op.f('ix_workflow_transition_instance_id'), 'workflow_transition', ['instance_id'], unique=False)
    op.add_column('intake_ticket', sa.Column('external_message_id', sa.String(), nullable=True))
    op.add_column('intake_ticket', sa.Column('workflow_instance_id', sa.String(), nullable=True))
    op.create_unique_constraint('uq_intake_ticket_org_external_message', 'intake_ticket', ['organization_id', 'external_message_id'])
    op.create_foreign_key(op.f('fk_intake_ticket_workflow_instance_id_workflow_instance'), 'intake_ticket', 'workflow_instance', ['workflow_instance_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_intake_ticket_workflow_instance_id_workflow_instance'), 'intake_ticket', type_='foreignkey')
    op.drop_constraint('uq_intake_ticket_org_external_message', 'intake_ticket', type_='unique')
    op.drop_column('intake_ticket', 'workflow_instance_id')
    op.drop_column('intake_ticket', 'external_message_id')
    op.drop_index(op.f('ix_workflow_transition_instance_id'), table_name='workflow_transition')
    op.drop_table('workflow_transition')
    op.drop_index(op.f('ix_workflow_agent_task_instance_id'), table_name='workflow_agent_task')
    op.drop_table('workflow_agent_task')
    op.drop_index(op.f('ix_workflow_step_definition_id'), table_name='workflow_step')
    op.drop_table('workflow_step')
    op.drop_index(op.f('ix_workflow_instance_status'), table_name='workflow_instance')
    op.drop_index(op.f('ix_workflow_instance_organization_id'), table_name='workflow_instance')
    op.drop_index('ix_workflow_instance_entity', table_name='workflow_instance')
    op.drop_index(op.f('ix_workflow_instance_definition_id'), table_name='workflow_instance')
    op.drop_table('workflow_instance')
    op.drop_index(op.f('ix_workflow_definition_organization_id'), table_name='workflow_definition')
    op.drop_table('workflow_definition')
    # ### end Alembic commands ###
