"""sanctions list, knowledge entries, mark portfolio

Revision ID: 978621b2b340
Revises: 0005_fts_indexes
Create Date: 2026-07-07 14:06:20.566980
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '978621b2b340'
down_revision: Union[str, None] = '0005_fts_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sanctions_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('list_source', sa.String(), nullable=False),
    sa.Column('list_version', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('program', sa.String(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sanctions_entry')),
    sa.UniqueConstraint('list_source', 'name', name='uq_sanctions_entry_source_name')
    )
    op.create_index(op.f('ix_sanctions_entry_name'), 'sanctions_entry', ['name'], unique=False)
    op.create_table('knowledge_entry',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('kind', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('owner_user_id', sa.String(), nullable=True),
    sa.Column('effective_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_due', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_knowledge_entry_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_knowledge_entry')),
    sa.UniqueConstraint('organization_id', 'kind', 'slug', 'version', name='uq_knowledge_entry_slug_version')
    )
    op.create_index('ix_knowledge_entry_current', 'knowledge_entry', ['organization_id', 'kind', 'is_current'], unique=False)
    op.create_index(op.f('ix_knowledge_entry_organization_id'), 'knowledge_entry', ['organization_id'], unique=False)
    op.create_table('mark',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('nice_classes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('jurisdictions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_mark_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_mark')),
    sa.UniqueConstraint('organization_id', 'name', name='uq_mark_org_name')
    )
    op.create_index(op.f('ix_mark_organization_id'), 'mark', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_mark_organization_id'), table_name='mark')
    op.drop_table('mark')
    op.drop_index(op.f('ix_knowledge_entry_organization_id'), table_name='knowledge_entry')
    op.drop_index('ix_knowledge_entry_current', table_name='knowledge_entry')
    op.drop_table('knowledge_entry')
    op.drop_index(op.f('ix_sanctions_entry_name'), table_name='sanctions_entry')
    op.drop_table('sanctions_entry')
    # ### end Alembic commands ###
