"""ontology embedding storage

Revision ID: c809863324e2
Revises: 065eae42b2ad
Create Date: 2026-07-07 18:43:38.018382
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c809863324e2'
down_revision: Union[str, None] = '065eae42b2ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_embedding',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('dim', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.ARRAY(sa.Float()), nullable=False),
    sa.Column('content_hash', sa.String(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_ontology_embedding_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_embedding')),
    sa.UniqueConstraint('organization_id', 'node_type', 'node_id', name='uq_ontology_embedding_node')
    )
    op.create_index(op.f('ix_ontology_embedding_organization_id'), 'ontology_embedding', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ontology_embedding_organization_id'), table_name='ontology_embedding')
    op.drop_table('ontology_embedding')
    # ### end Alembic commands ###
