"""ontology edges, agent decisions, ai call log

Revision ID: d61aee16e3e7
Revises: 0002_audit_chain
Create Date: 2026-07-07 11:44:28.891410
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'd61aee16e3e7'
down_revision: Union[str, None] = '0002_audit_chain'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_call_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_chars', sa.Integer(), nullable=False),
    sa.Column('response_chars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_call_log'))
    )
    op.create_index('ix_ai_call_log_org_created', 'ai_call_log', ['organization_id', 'created_at'], unique=False)
    op.create_table('agent_decision',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('action_key', sa.String(), nullable=False),
    sa.Column('action_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommendation', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('decided_by', sa.String(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('executed_audit_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_agent_decision_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_decision'))
    )
    op.create_index('ix_agent_decision_org_status', 'agent_decision', ['organization_id', 'status'], unique=False)
    op.create_index(op.f('ix_agent_decision_organization_id'), 'agent_decision', ['organization_id'], unique=False)
    op.create_index('ix_agent_decision_resource', 'agent_decision', ['organization_id', 'resource_type', 'resource_id'], unique=False)
    op.create_index(op.f('ix_agent_decision_status'), 'agent_decision', ['status'], unique=False)
    op.create_table('ontology_edge',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('src_type', sa.String(), nullable=False),
    sa.Column('src_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('dst_type', sa.String(), nullable=False),
    sa.Column('dst_id', sa.String(), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_module', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_ontology_edge_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_edge')),
    sa.UniqueConstraint('organization_id', 'src_type', 'src_id', 'label', 'dst_type', 'dst_id', name='uq_ontology_edge_identity')
    )
    op.create_index('ix_ontology_edge_dst', 'ontology_edge', ['organization_id', 'dst_type', 'dst_id'], unique=False)
    op.create_index('ix_ontology_edge_label', 'ontology_edge', ['organization_id', 'label'], unique=False)
    op.create_index(op.f('ix_ontology_edge_organization_id'), 'ontology_edge', ['organization_id'], unique=False)
    op.create_index('ix_ontology_edge_src', 'ontology_edge', ['organization_id', 'src_type', 'src_id'], unique=False)
    # NOTE: autogenerate proposed dropping uq_audit_log_org_chain_position
    # because migration 0002 created it outside the ORM. That index is
    # load-bearing (a duplicate chain position means a trigger bypass) and is
    # now declared on the AuditLog model — the drop was removed by hand.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ontology_edge_src', table_name='ontology_edge')
    op.drop_index(op.f('ix_ontology_edge_organization_id'), table_name='ontology_edge')
    op.drop_index('ix_ontology_edge_label', table_name='ontology_edge')
    op.drop_index('ix_ontology_edge_dst', table_name='ontology_edge')
    op.drop_table('ontology_edge')
    op.drop_index(op.f('ix_agent_decision_status'), table_name='agent_decision')
    op.drop_index('ix_agent_decision_resource', table_name='agent_decision')
    op.drop_index(op.f('ix_agent_decision_organization_id'), table_name='agent_decision')
    op.drop_index('ix_agent_decision_org_status', table_name='agent_decision')
    op.drop_table('agent_decision')
    op.drop_index('ix_ai_call_log_org_created', table_name='ai_call_log')
    op.drop_table('ai_call_log')
    # ### end Alembic commands ###
