"""initial shared entities and intake

Revision ID: fcdad2d98ec6
Revises: 
Create Date: 2026-07-07 09:30:07.376720
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fcdad2d98ec6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('tier', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('actor_type', sa.String(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('resource_type', sa.String(), nullable=False),
    sa.Column('resource_id', sa.String(), nullable=False),
    sa.Column('before_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('prev_hash', sa.String(), server_default='', nullable=False),
    sa.Column('content_hash', sa.String(), server_default='', nullable=False),
    sa.Column('chain_position', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('schema_version', sa.Integer(), server_default='1', nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_audit_log_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_log'))
    )
    op.create_index(op.f('ix_audit_log_organization_id'), 'audit_log', ['organization_id'], unique=False)
    op.create_table('counterparty',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('sanctions_screened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_counterparty_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['counterparty.id'], name=op.f('fk_counterparty_parent_id_counterparty'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_counterparty'))
    )
    op.create_index(op.f('ix_counterparty_organization_id'), 'counterparty', ['organization_id'], unique=False)
    op.create_table('document',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('mime_type', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('storage_url', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_document_id', sa.String(), nullable=True),
    sa.Column('owner_type', sa.String(), nullable=False),
    sa.Column('owner_id', sa.String(), nullable=False),
    sa.Column('uploaded_by', sa.String(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extracted_text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_document_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_document_id'], ['document.id'], name=op.f('fk_document_parent_document_id_document'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document'))
    )
    op.create_index(op.f('ix_document_organization_id'), 'document', ['organization_id'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('actor_id', sa.String(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('indexed_for_search', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_event_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event'))
    )
    op.create_index(op.f('ix_event_organization_id'), 'event', ['organization_id'], unique=False)
    op.create_table('obligation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('recurrence', sa.String(), nullable=True),
    sa.Column('owner_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_obligation_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_obligation'))
    )
    op.create_index(op.f('ix_obligation_organization_id'), 'obligation', ['organization_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_role_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role'))
    )
    op.create_index(op.f('ix_role_organization_id'), 'role', ['organization_id'], unique=False)
    op.create_table('tag',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_tag_organization_id_organization'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tag'))
    )
    op.create_index(op.f('ix_tag_organization_id'), 'tag', ['organization_id'], unique=False)
    op.create_table('app_user',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_app_user_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_app_user_role_id_role'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user'))
    )
    op.create_index(op.f('ix_app_user_organization_id'), 'app_user', ['organization_id'], unique=False)
    op.create_index(op.f('ix_app_user_role_id'), 'app_user', ['role_id'], unique=False)
    op.create_table('tagging',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('tag_id', sa.String(), nullable=False),
    sa.Column('tagged_type', sa.String(), nullable=False),
    sa.Column('tagged_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], name=op.f('fk_tagging_tag_id_tag'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tagging'))
    )
    op.create_index(op.f('ix_tagging_tag_id'), 'tagging', ['tag_id'], unique=False)
    op.create_table('person',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('external_ref', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_person_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_person_user_id_app_user'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person'))
    )
    op.create_index(op.f('ix_person_organization_id'), 'person', ['organization_id'], unique=False)
    op.create_index(op.f('ix_person_user_id'), 'person', ['user_id'], unique=False)
    op.create_table('intake_ticket',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('organization_id', sa.String(), nullable=False),
    sa.Column('requester_id', sa.String(), nullable=False),
    sa.Column('matter_id', sa.String(), nullable=True),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('stage', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('assigned_to', sa.String(), nullable=True),
    sa.Column('assigned_to_user_id', sa.String(), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=False),
    sa.Column('sla_status', sa.String(), nullable=False),
    sa.Column('ai_triage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('triaged_by', sa.String(), nullable=True),
    sa.Column('triaged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('triaged_action', sa.String(), nullable=True),
    sa.Column('agent_processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_user_id'], ['app_user.id'], name=op.f('fk_intake_ticket_assigned_to_user_id_app_user'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], name=op.f('fk_intake_ticket_organization_id_organization'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['person.id'], name=op.f('fk_intake_ticket_requester_id_person'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_intake_ticket'))
    )
    op.create_index(op.f('ix_intake_ticket_organization_id'), 'intake_ticket', ['organization_id'], unique=False)
    op.create_index(op.f('ix_intake_ticket_requester_id'), 'intake_ticket', ['requester_id'], unique=False)
    op.create_index(op.f('ix_intake_ticket_status'), 'intake_ticket', ['status'], unique=False)
    op.create_table('agent_recommendation',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('ticket_id', sa.String(), nullable=False),
    sa.Column('agent_id', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggested_action', sa.String(), nullable=False),
    sa.Column('drafted_response', sa.Text(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('concerns', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('citations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('short_form_reply', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reviewed_by', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['intake_ticket.id'], name=op.f('fk_agent_recommendation_ticket_id_intake_ticket'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_recommendation'))
    )
    op.create_index(op.f('ix_agent_recommendation_status'), 'agent_recommendation', ['status'], unique=False)
    op.create_index(op.f('ix_agent_recommendation_ticket_id'), 'agent_recommendation', ['ticket_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_recommendation_ticket_id'), table_name='agent_recommendation')
    op.drop_index(op.f('ix_agent_recommendation_status'), table_name='agent_recommendation')
    op.drop_table('agent_recommendation')
    op.drop_index(op.f('ix_intake_ticket_status'), table_name='intake_ticket')
    op.drop_index(op.f('ix_intake_ticket_requester_id'), table_name='intake_ticket')
    op.drop_index(op.f('ix_intake_ticket_organization_id'), table_name='intake_ticket')
    op.drop_table('intake_ticket')
    op.drop_index(op.f('ix_person_user_id'), table_name='person')
    op.drop_index(op.f('ix_person_organization_id'), table_name='person')
    op.drop_table('person')
    op.drop_index(op.f('ix_tagging_tag_id'), table_name='tagging')
    op.drop_table('tagging')
    op.drop_index(op.f('ix_app_user_role_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_organization_id'), table_name='app_user')
    op.drop_table('app_user')
    op.drop_index(op.f('ix_tag_organization_id'), table_name='tag')
    op.drop_table('tag')
    op.drop_index(op.f('ix_role_organization_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_obligation_organization_id'), table_name='obligation')
    op.drop_table('obligation')
    op.drop_index(op.f('ix_event_organization_id'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_document_organization_id'), table_name='document')
    op.drop_table('document')
    op.drop_index(op.f('ix_counterparty_organization_id'), table_name='counterparty')
    op.drop_table('counterparty')
    op.drop_index(op.f('ix_audit_log_organization_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('organization')
    # ### end Alembic commands ###
